package jp.pirijuggler.paper.game.god;

/** Fixed Piri GOD loop-stock classes. */
public enum GodLoopType {
    A(0.01),
    B(0.25),
    C(0.50),
    D(0.80);

    private final double continuationRate;

    GodLoopType(double continuationRate) {
        this.continuationRate = continuationRate;
    }

    public double continuationRate() {
        return continuationRate;
    }

    /** Expected number of extra GG stocks generated by one loop stock. */
    public double expectedExtraStocks() {
        return continuationRate / (1.0 - continuationRate);
    }
}
