package jp.pirijuggler.paper.game.pachinko;

/**
 * Locked baseline economics for the first pachinko machine.
 *
 * The 1000-yen equivalent assumes 4-yen pachinko: 250 balls per 1000 yen.
 * Border is derived from the other values; it is not a separately tuned payout knob.
 */
public final class PachinkoSpec {
    public static final double INITIAL_JACKPOT_DENOMINATOR = 319.0;
    public static final int BALLS_PER_1000_YEN = 250;
    public static final int START_PRIZE_BALLS = 1;

    public static final double RUSH_ENTRY_RATE = 0.60;
    public static final int NORMAL_INITIAL_PAYOUT = 450;
    public static final int RUSH_INITIAL_PAYOUT = 1500;

    public static final double RUSH_CONTINUATION_RATE = 0.81;
    public static final double RIGHT_1500_RATE = 0.97;
    public static final double RIGHT_3000_RATE = 0.03;
    public static final int RIGHT_1500_PAYOUT = 1500;
    public static final int RIGHT_3000_PAYOUT = 3000;

    /** Reference playability target, not the break-even border. */
    public static final double REFERENCE_SPINS_PER_1000_YEN = 17.0;

    private PachinkoSpec() {}

    public static double averageRightPayout() {
        return RIGHT_1500_RATE * RIGHT_1500_PAYOUT + RIGHT_3000_RATE * RIGHT_3000_PAYOUT;
    }

    /**
     * Number of right-side wins after entering RUSH.
     * A continuation probability of c yields c/(1-c) additional wins on average.
     */
    public static double expectedRightWinsAfterEntry() {
        return RUSH_CONTINUATION_RATE / (1.0 - RUSH_CONTINUATION_RATE);
    }

    /** Gross prize balls generated by one initial jackpot on average. */
    public static double expectedGrossPayoutPerInitialJackpot() {
        double normal = (1.0 - RUSH_ENTRY_RATE) * NORMAL_INITIAL_PAYOUT;
        double rush = RUSH_ENTRY_RATE * (
                RUSH_INITIAL_PAYOUT + expectedRightWinsAfterEntry() * averageRightPayout()
        );
        return normal + rush;
    }

    /**
     * Equivalent break-even spins per 1000 yen.
     * Start prize is returned for every start, so net burn per start is
     * 250/spins - START_PRIZE_BALLS.
     */
    public static double equivalentBorderSpinsPer1000Yen() {
        double expectedPayoutPerStart = expectedGrossPayoutPerInitialJackpot() / INITIAL_JACKPOT_DENOMINATOR;
        return BALLS_PER_1000_YEN / (expectedPayoutPerStart + START_PRIZE_BALLS);
    }

    /**
     * Theoretical payout rate for a measured spin rate.
     * 100 means break-even under this model.
     */
    public static double payoutRatePercent(double spinsPer1000Yen) {
        if (!(spinsPer1000Yen > 0.0)) throw new IllegalArgumentException("spinsPer1000Yen");
        double netBallCostPerStart = BALLS_PER_1000_YEN / spinsPer1000Yen - START_PRIZE_BALLS;
        if (!(netBallCostPerStart > 0.0)) throw new IllegalArgumentException("spin rate exceeds physical model");
        double expectedInputToInitialJackpot = INITIAL_JACKPOT_DENOMINATOR * netBallCostPerStart;
        return expectedGrossPayoutPerInitialJackpot() / expectedInputToInitialJackpot * 100.0;
    }
}
