package jp.pirijuggler.common.protocol;

public enum ErrorCode {
    BUSY, INVALID_STATE, NOT_ENOUGH_CREDIT, ECONOMY_UNAVAILABLE, NOT_ENOUGH_VAULT,
    NOT_ENOUGH_MEDALS, INVENTORY_FULL, MACHINE_OCCUPIED, MACHINE_DISABLED,
    SESSION_MISMATCH, SEQUENCE_OLD, SPIN_MISMATCH, STOP_TOO_EARLY, ALREADY_STOPPED,
    NOT_OP, INVALID_ITEM, TOKEN_REVIEW_REQUIRED, DB_ERROR, VAULT_ERROR, PROTOCOL_MISMATCH
}
