package jp.pirijuggler.paper.game;

/**
 * Closed-form Phase 03 expectation model for bonus-in-bonus stock.
 * No RNG: this is the theory source used before Monte Carlo verification.
 */
public final class JugglerGodTheory {
    private static final double GOD_P = 1.0 / 8192.0;
    private static final int BIG_GAMES = 20;
    private static final int REG_GAMES = 8;
    private static final double BIG_NET = 239.0;
    private static final double REG_NET = 95.0;
    private static final int GOD_IN_GOD_BIG_STOCK = 7;
    private static final int[] CONTINUATION_PERCENT={0,75,78,80,82,85,90};

    public record Result(
            int setting,
            double effectiveBigPerBonusGame,
            double effectiveRegPerBonusGame,
            double godPerBonusGame,
            double reproductionRadius,
            double bigsFromOneGodBigStock,
            double regsFromOneGodBigStock,
            double netFromOneGodBigStock,
            double godInGodHitsFromOneGodBigStock,
            double outerGodExpectedBaseBigSeeds,
            double outerGodExpectedTotalBigs,
            double outerGodExpectedTotalRegs,
            double outerGodExpectedGodInGodHits,
            double outerGodExpectedNetBeforeHeaven
    ) {}

    public static Result calculate(RoleWeights weights,int setting,int bonusScalePpm){
        if(setting<1||setting>6)throw new IllegalArgumentException("setting");
        long bigWeight=weights.bonusFamilyWeight(setting,true,bonusScalePpm);
        long regWeight=weights.bonusFamilyWeight(setting,false,bonusScalePpm);

        // Production ordering is GOD first. Only when GOD misses is the regular role table drawn.
        double nonGod=1.0-GOD_P;
        double pBig=nonGod*bigWeight/RoleWeights.DENOMINATOR;
        double pReg=nonGod*regWeight/RoleWeights.DENOMINATOR;

        // During an active GOD, GOD-in-GOD contributes seven BIG stocks rather than starting a second chain.
        double qBig=pBig+GOD_P*GOD_IN_GOD_BIG_STOCK;
        double qReg=pReg;
        double radius=BIG_GAMES*qBig+REG_GAMES*qReg;
        if(radius>=1.0)throw new IllegalStateException("Supercritical bonus-stock chain");

        double a=1.0-BIG_GAMES*qBig;
        double b=-BIG_GAMES*qReg;
        double c=-REG_GAMES*qBig;
        double d=1.0-REG_GAMES*qReg;
        double det=a*d-b*c;

        // Expected total bonus counts generated by one BIG stock, including the seed itself.
        double totalBigFromBig=d/det;
        double totalRegFromBig=(-c)/det;

        // Expected GOD-in-GOD hit count. RHS is the direct GOD chance in each seed's bonus games.
        double rhsBigGig=BIG_GAMES*GOD_P;
        double rhsRegGig=REG_GAMES*GOD_P;
        double gigFromBig=(rhsBigGig*d-b*rhsRegGig)/det;

        // Net medal expectation includes each bonus's own net and the 15-medal GOD role payout.
        double rhsBigNet=BIG_NET+BIG_GAMES*GOD_P*15.0;
        double rhsRegNet=REG_NET+REG_GAMES*GOD_P*15.0;
        double netFromBig=(rhsBigNet*d-b*rhsRegNet)/det;

        double continuation=CONTINUATION_PERCENT[setting]/100.0;
        double baseSeeds=5.0+continuation/(1.0-continuation);

        return new Result(
                setting,pBig,pReg,GOD_P,radius,
                totalBigFromBig,totalRegFromBig,netFromBig,gigFromBig,
                baseSeeds,
                baseSeeds*totalBigFromBig,
                baseSeeds*totalRegFromBig,
                baseSeeds*gigFromBig,
                15.0+baseSeeds*netFromBig
        );
    }

    private JugglerGodTheory(){}
}
